<?php
$parameters = array(
	'db_driver' => 'pdo_mysql',
	'db_host' => 'localhost',
	'db_table_prefix' => null,
	'db_port' => '3306',
	'db_name' => 'mautic',
	'db_user' => 'mautic-user',
	'db_password' => 'h6MeJC4TXZ4b2ppH',
	'db_backup_tables' => 0,
	'db_backup_prefix' => 'bak_',
	'db_server_version' => '5.5.5-10.0.35-MariaDB',
	'mailer_from_name' => 'Kevin Jiang',
	'mailer_from_email' => 'kevin@accesspath.com',
	'mailer_transport' => 'mail',
	'mailer_host' => null,
	'mailer_port' => null,
	'mailer_user' => null,
	'mailer_password' => null,
	'mailer_encryption' => null,
	'mailer_auth_mode' => null,
	'mailer_spool_type' => 'memory',
	'mailer_spool_path' => '%kernel.root_dir%/spool',
	'secret_key' => 'f770aefba910870fb6b6ded9120b0629663f0d88f842a3e130f91a646a41af77',
	'site_url' => 'http://pro.accesspath.com/index.php',
);
